export type JokerName = keyof typeof JOKERS;
export type JokerConfig = (typeof JOKERS)[keyof typeof JOKERS];
export type JokerHand = {
  [key in JokerName]?: number;
};
type JokerAbility = {
  negative?: boolean;
  eternal?: boolean;
};

function knownJoker(joker: JokerName | string) {
  return Object.keys(JOKERS).includes(joker);
}

function addJoker(joker: JokerName, options?: JokerAbility) {
  if (!knownJoker(joker)) return new Error(`Not implemented joker: ${joker}`);
  return JOKERS[joker];
}

export function generateJokers(jokers: JokerHand, options?: JokerAbility) {
  const jokerArray = Object.entries(jokers).map(([joker, amount]) => {
    if (knownJoker(joker as JokerName)) {
      return Array(amount).fill(addJoker(joker as JokerName));
    }
  });

  const data = jokerArray
    .flat()
    .filter((joker) => joker !== undefined)
    .map((joker: JokerConfig, index) => {
      return {
        ...joker,
        rank: index + 1,
      };
    });
  return data;
}

export const JOKERS = {
  baron: {
    base_cost: 8,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 4,
      h_mult: 0,
      set: "Joker",
      extra: 1.5,
      order: 72,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Baron",
      perma_bonus: 0,
      bonus: 0,
      type: "",
      extra_value: 2,
      eternal: true,
      mult: 0,
    },
    save_fields: {
      center: "j_baron",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 8,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 97,
    sort_id: 2086,
    debuff: false,
    label: "Baron",
  },
  wee: {
    base_cost: 8,
    extra_cost: 0,
    params: {
      discover: true,
      bypass_discovery_center: true,
      bypass_back: {
        y: 3,
        x: 3,
      },
    },
    rank: 205,
    bypass_discovery_ui: true,
    facing: "front",
    save_fields: {
      center: "j_wee",
    },
    ability: {
      order: 124,
      type: "",
      t_mult: 0,
      h_mult: 0,
      h_size: 0,
      d_size: 0,
      t_chips: 0,
      bonus: 0,
      perma_bonus: 0,
      h_x_mult: 0,
      h_dollars: 0,
      extra: {
        chips: 10,
        chip_mod: 8,
      },
      p_dollars: 0,
      set: "Joker",
      hands_played_at_create: 14,
      x_mult: 1,
      mult: 0,
      effect: "",
      name: "Wee Joker",
      extra_value: 0,
    },
    debuff: false,
    label: "Wee Joker",
    bypass_discovery_center: true,
    cost: 6,
    sell_cost: 3,
    sprite_facing: "front",
    sort_id: 1575,
    added_to_deck: true,
    bypass_lock: true,
    base: {
      nominal: 0,
      suit_nominal: 0,
      face_nominal: 0,
      times_played: 0,
    },
  },
  hack: {
    base_cost: 6,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      set: "Joker",
      extra: 1,
      order: 36,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Hack",
      perma_bonus: 0,
      bonus: 0,
      effect: "Low Card double",
      type: "",
      extra_value: 3,
      h_mult: 0,
      mult: 0,
    },
    save_fields: {
      center: "j_hack",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 6,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 1,
    sort_id: 1498,
    debuff: false,
    label: "Hack",
  },
  spaceJoker: {
    base_cost: 5,
    extra_cost: 3,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      h_mult: 0,
      set: "Joker",
      extra: 4,
      order: 45,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Space Joker",
      perma_bonus: 0,
      bonus: 0,
      effect: "Upgrade Hand chance",
      type: "",
      extra_value: 3,
      mult: 0,
    },
    save_fields: {
      center: "j_space",
    },
    added_to_deck: true,
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 8,
    sell_cost: 7,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 75,
    sort_id: 1610,
    debuff: false,
    label: "Space Joker",
  },
  hiker: {
    base_cost: 5,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      h_mult: 0,
      set: "Joker",
      extra: 4,
      order: 56,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Hiker",
      perma_bonus: 0,
      bonus: 0,
      type: "",
      extra_value: 4,
      mult: 0,
    },
    save_fields: {
      center: "j_hiker",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 5,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 56,
    sort_id: 1410,
    debuff: false,
    label: "Hiker",
  },
  dna: {
    base_cost: 8,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 1,
      set: "Joker",
      order: 51,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "DNA",
      perma_bonus: 0,
      bonus: 0,
      type: "",
      extra_value: 5,
      mult: 0,
      h_mult: 0,
    },
    save_fields: {
      center: "j_dna",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 8,
    sell_cost: 9,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 10,
    sort_id: 225,
    debuff: false,
    label: "DNA",
  },
  oopsAll6s: {
    base_cost: 4,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 1,
      h_mult: 0,
      set: "Joker",
      order: 126,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Oops! All 6s",
      perma_bonus: 0,
      bonus: 0,
      effect: "",
      type: "",
      extra_value: 5,
      mult: 0,
    },
    save_fields: {
      center: "j_oops",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 4,
    sell_cost: 7,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 20,
    sort_id: 458,
    debuff: false,
    label: "Oops! All 6s",
  },
  showman: {
    base_cost: 5,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 2,
      h_mult: 0,
      set: "Joker",
      order: 121,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Showman",
      perma_bonus: 0,
      bonus: 0,
      effect: "",
      type: "",
      extra_value: 4,
      mult: 0,
    },
    save_fields: {
      center: "j_ring_master",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 5,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 54,
    sort_id: 1327,
    debuff: false,
    label: "Showman",
  },
  burntJoker: {
    base_cost: 6,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 4,
      set: "Joker",
      extra: 4,
      order: 144,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Burnt Joker",
      perma_bonus: 0,
      bonus: 0,
      effect: "",
      type: "",
      extra_value: 2,
      h_mult: 0,
      mult: 0,
    },
    save_fields: {
      center: "j_burnt",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 6,
    sell_cost: 5,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 96,
    sort_id: 2061,
    debuff: false,
    label: "Burnt Joker",
  },
  fibonacci: {
    base_cost: 7,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 4,
      h_mult: 0,
      set: "Joker",
      extra: 8,
      order: 31,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Fibonacci",
      perma_bonus: 0,
      bonus: 0,
      effect: "Card Mult",
      type: "",
      extra_value: 2,
      mult: 0,
    },
    save_fields: {
      center: "j_fibonacci",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 7,
    sell_cost: 5,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
  },
};
