export type Joker = keyof typeof JOKERS;

export const JOKERS = {
  hack: {
    base_cost: 6,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      eternal: true,
      set: "Joker",
      extra: 1,
      order: 36,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Hack",
      perma_bonus: 0,
      bonus: 0,
      effect: "Low Card double",
      type: "",
      extra_value: 3,
      h_mult: 0,
      mult: 0,
    },
    save_fields: {
      center: "j_hack",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 6,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 1,
    sort_id: 1498,
    debuff: false,
    label: "Hack",
  },
  spaceJoker: {
    base_cost: 5,
    extra_cost: 3,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      h_mult: 0,
      set: "Joker",
      extra: 4,
      order: 45,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Space Joker",
      perma_bonus: 0,
      bonus: 0,
      effect: "Upgrade Hand chance",
      type: "",
      extra_value: 3,
      mult: 0,
    },
    save_fields: {
      center: "j_space",
    },
    added_to_deck: true,
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 8,
    sell_cost: 7,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    edition: {
      holo: true,
      type: "holo",
      mult: 10,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 75,
    sort_id: 1610,
    debuff: false,
    label: "Space Joker",
  },
  hiker: {
    base_cost: 5,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 0,
      h_mult: 0,
      set: "Joker",
      extra: 4,
      order: 56,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Hiker",
      perma_bonus: 0,
      bonus: 0,
      type: "",
      extra_value: 4,
      mult: 0,
    },
    save_fields: {
      center: "j_hiker",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 5,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 56,
    sort_id: 1410,
    debuff: false,
    label: "Hiker",
  },
  dna: {
    base_cost: 8,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 1,
      eternal: true,
      set: "Joker",
      order: 51,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "DNA",
      perma_bonus: 0,
      bonus: 0,
      type: "",
      extra_value: 5,
      mult: 0,
      h_mult: 0,
    },
    save_fields: {
      center: "j_dna",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 8,
    sell_cost: 9,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 10,
    sort_id: 225,
    debuff: false,
    label: "DNA",
  },
  oopsAll6s: {
    base_cost: 4,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 1,
      h_mult: 0,
      set: "Joker",
      order: 126,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Oops! All 6s",
      perma_bonus: 0,
      bonus: 0,
      effect: "",
      type: "",
      extra_value: 5,
      eternal: true,
      mult: 0,
    },
    save_fields: {
      center: "j_oops",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 4,
    sell_cost: 7,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 20,
    sort_id: 458,
    debuff: false,
    label: "Oops! All 6s",
  },
  showman: {
    base_cost: 5,
    extra_cost: 0,
    facing: "front",
    ability: {
      h_x_mult: 0,
      t_chips: 0,
      x_mult: 1,
      h_dollars: 0,
      p_dollars: 0,
      hands_played_at_create: 2,
      h_mult: 0,
      set: "Joker",
      order: 121,
      d_size: 0,
      t_mult: 0,
      h_size: 0,
      name: "Showman",
      perma_bonus: 0,
      bonus: 0,
      effect: "",
      type: "",
      extra_value: 4,
      mult: 0,
    },
    save_fields: {
      center: "j_ring_master",
    },
    bypass_discovery_center: true,
    bypass_discovery_ui: true,
    cost: 5,
    sell_cost: 6,
    base: {
      face_nominal: 0,
      times_played: 0,
      nominal: 0,
      suit_nominal: 0,
    },
    added_to_deck: true,
    params: {
      bypass_discovery_ui: true,
      bypass_back: {
        y: 2,
        x: 6,
      },
      discover: false,
      bypass_discovery_center: true,
    },
    bypass_lock: true,
    sprite_facing: "front",
    rank: 54,
    sort_id: 1327,
    debuff: false,
    label: "Showman",
  },
};
